server:
  forward-headers-strategy: framework

oereb: 
    endpoints:
        - identifier: SO
          SERVICE_ENDPOINT: https://geo.so.ch/api/oereb/
          EN: 2600595,1215629
          IDENTDN: SO0200002457
          NUMBER: 168
          EGRID: CH807306583219
        - identifier: UR
          SERVICE_ENDPOINT: https://prozessor-oereb.ur.ch/oereb/
          EN: 2694124,1180546
          IDENTDN: UR0200001216
          NUMBER: 112
          EGRID: CH727993074655
