server:
  servlet:
    session:
      tracking-modes: 'cookie'

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
     
spring:
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:54321/edit}
    driverClassName: ${DB_DRIVER_CLASSNAME:org.postgresql.Driver}
    username: ${DB_USR:ddluser}
    password: ${DB_PWD:ddluser}
 
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    ch.so.agi.oereb: ${LOG_LEVEL_APP:DEBUG} 
    com.zaxxer.hikari: ${LOG_LEVEL_DB_CONNECTION_POOL:INFO}

app:
  checkCronExpression: ${CHECK_CRON_EXPRESSION:0 0 */4 * * *}
  workDirectory: ${WORK_DIRECTORY:#{systemProperties['java.io.tmpdir']}}
  folderPrefix: ${FOLDER_PREFIX:oerebcts}
  database:
    schema: ${DB_SCHEMA:agi_oereb_cts_v1}
    testQuery: ${DB_TEST_QUERY:SELECT * FROM agi_oereb_cts_v1.proberesult LIMIT 1}
    createOnStartup: ${DB_CREATE_ON_STARTUP:false}
  testSuite:
    validateOnStartup: ${CTS_VALIDATE_ON_STARTUP:false}

oereb: 
    services:
        - identifier: AG
          SERVICE_ENDPOINT: https://api.geo.ag.ch/v2/oereb/
          EN: 2645569,1248779
          IDENTDN: AG0200004001
          NUMBER: 1401
          EGRID: CH832377520646
        - identifier: AI
          SERVICE_ENDPOINT: https://oereb.ai.ch/ktai/wsgi/oereb/
          EN: 2748586,1244111
          IDENTDN: AI02003101
          NUMBER: 313
          EGRID: CH967759413925
        - identifier: AR
          SERVICE_ENDPOINT: https://oereb.ar.ch/ktar/wsgi/oereb/
          EN: 2747517,1250484
          IDENTDN: AR0200302400
          NUMBER: 123
          EGRID: CH795277802170
        - identifier: BE
          SERVICE_ENDPOINT: https://www.oereb2.apps.be.ch/
          EN: 2600190,1199244
          IDENTDN: BE0200000044
          NUMBER: 573
          EGRID: CH968746351907
        - identifier: BL
          SERVICE_ENDPOINT: https://oereb.geo.bl.ch/
          EN: 2611819,1260126
          IDENTDN: BL0200002773
          NUMBER: 6132
          EGRID: CH767982496078
        - identifier: BS
          SERVICE_ENDPOINT: https://api.oereb.bs.ch/
          EN: 2612855,1267223
          IDENTDN: BSS500000000
          NUMBER: 2162
          EGRID: CH356489796755
        - identifier: FR
          SERVICE_ENDPOINT: https://geo.fr.ch/RDPPF_ws/RdppfSVC.svc/
          EN: 2578478,1183785
          IDENTDN: FR219611
          NUMBER: 17521
          EGRID: CH831076942864
        - identifier: GR
          SERVICE_ENDPOINT: https://oereb.geo.gr.ch/oereb/
          EN: 2759467,1191198
          IDENTDN: GR0000003901
          NUMBER: 1638
          EGRID: CH587686687752
        - identifier: JU
          SERVICE_ENDPOINT: https://geo.jura.ch/crdppf_server/
          EN: 2592766,1245889
          IDENTDN: "6711_1163" # Anführungszeichen sind notwendig, sonst verschwindet der Underscore.
          NUMBER: 1163
          EGRID: CH110696447807
        - identifier: LU
          SERVICE_ENDPOINT: https://svc.geo.lu.ch/oereb/
          EN: 2666237,1211859
          IDENTDN: LU04GBPER112
          NUMBER: 4034
          EGRID: CH695089003582
        - identifier: NE
          SERVICE_ENDPOINT: https://sitn.ne.ch/crdppf/
          EN: 2560587,1204510
          IDENTDN: NE011378
          NUMBER: 1378
          EGRID: CH618727497802
        - identifier: NW
          SERVICE_ENDPOINT: https://oereb.gis-daten.ch/oereb/
          EN: 2672226,1201394
          IDENTDN: NW0200001508
          NUMBER: 133
          EGRID: CH233477054456
        - identifier: OW
          SERVICE_ENDPOINT: https://oereb.gis-daten.ch/oereb/
          EN: 2661273,1191346
          IDENTDN: OW0200001406
          NUMBER: 196
          EGRID: CH913620047721
        - identifier: SG
          SERVICE_ENDPOINT: https://oereb.geo.sg.ch/ktsg/wsgi/oereb/
          EN: 2746774,1255302
          IDENTDN: SG0200320300
          NUMBER: C1556
          EGRID: CH427712875908
        - identifier: SH
          SERVICE_ENDPOINT: https://oereb.geo.sh.ch/
          EN: 2688880,1284658 
          IDENTDN: SH0200002939
          NUMBER: 1582
          EGRID: CH915411087888
        - identifier: SO
          SERVICE_ENDPOINT: https://geo.so.ch/api/oereb/
          EN: 2600595,1215629
          IDENTDN: SO0200002457
          NUMBER: 168
          EGRID: CH807306583219
        - identifier: TG
          SERVICE_ENDPOINT: https://map.geo.tg.ch/services/oereb/
          EN: 2709869,1268547
          IDENTDN: TG4566
          NUMBER: 436
          EGRID: CH427705802925
        - identifier: TI
          SERVICE_ENDPOINT: https://cloud.geo.ti.ch/oereb2/
          EN: 2705427,1114471
          IDENTDN: TI43000
          NUMBER: 190
          EGRID: CH230298071872
        - identifier: UR
          SERVICE_ENDPOINT: https://prozessor-oereb.ur.ch/oereb/
          EN: 2694124,1180546
          IDENTDN: UR0200001216
          NUMBER: 112
          EGRID: CH727993074655
        - identifier: VS
          SERVICE_ENDPOINT: https://rdppfvs.geopol.ch/
          EN: 2643445,1130616
          #IDENTDN= fehlt in XML
          #NUMBER=6918
          EGRID: CH595290323059
        - identifier: ZG
          SERVICE_ENDPOINT: https://oereb.zg.ch/ors/
          EN: 2681396,1225658
          IDENTDN: ZG0200001711
          NUMBER: 289
          EGRID: CH187006657415
        - identifier: ZH
          SERVICE_ENDPOINT: https://maps.zh.ch/oereb/v2/
          EN: 2683914,1248184
          IDENTDN: ZH0200000261
          NUMBER: OB4248
          EGRID: CH699970989135

