version: '3'
services:

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      DOZZLE_USERNAME: admin
      DOZZLE_PASSWORD: admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  edit-db:
    image: bitnami/postgresql:14.8.0-debian-11-r74
    restart: unless-stopped
    environment:
      POSTGRESQL_DATABASE: edit
      POSTGRESQL_USERNAME: ddluser
      POSTGRESQL_PASSWORD: ddluser
      POSTGRESQL_POSTGRES_PASSWORD: secret
      POSTGRESQL_INITSCRIPTS_USERNAME: postgres
      POSTGRESQL_INITSCRIPTS_PASSWORD: secret
      TZ: Europe/Zurich
    ports:
      - "54321:5432"
    volumes:
      - type: bind
        source: ./setup.sql
        target: /docker-entrypoint-preinitdb.d/setup.sql
      - type: bind
        source: ./prepare_setup.sh
        target: /docker-entrypoint-preinitdb.d/prepare_setup.sh
      - type: volume
        source: postgresql_data_edit
        target: /bitnami/postgresql
    labels:
      org.springframework.boot.service-connection: postgres

  frontend:
    image: sogis/oereb-cts:0
    restart: unless-stopped
    environment:
      TZ: Europe/Zurich
      DB_HOST: jdbc:postgresql://edit-db:5432/edit
      DB_CREATE_ON_STARTUP: true
      CTS_VALIDATE_ON_STARTUP: false
    entrypoint: "java -XX:+UseParallelGC -Xmx4G -jar application.jar --spring.profiles.active=docker"
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.frontend.rule=Host(`monitoring-oereb.localhost`) || Host(`monitoring.oereb.services`)"
      - "traefik.http.routers.frontend.rule=Host(`monitoring.oereb.services`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  reverse-proxy:
    image: traefik:v2.10
    restart: unless-stopped
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=stefan.ziegler.de@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgresql_data_edit:
